<a href="https://colab.research.google.com/github/tezendrax/Deep-Learning-Labs/blob/main/DL_Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)


2.11.0+cpu


In [ ]:
a = torch.tensor([1,3,456,55.69])
print(a)

tensor([  1.0000,   3.0000, 456.0000,  55.6900])


In [ ]:
print(a.shape)

torch.Size([4])


In [ ]:
t = torch.tensor([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print(t.shape)

torch.Size([2, 2, 2])


In [ ]:
torch.zeros((3,4))


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.rand((2,9))


tensor([[0.9821, 0.4787, 0.4557, 0.8550, 0.6463, 0.2027, 0.7755, 0.0680, 0.9959],
        [0.8484, 0.1081, 0.4598, 0.7006, 0.5262, 0.4711, 0.1236, 0.6471, 0.0943]])

In [ ]:
torch.ones((4,6))


tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [ ]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [ ]:
A = torch.tensor([[1,2],
                  [3,4]])

B = torch.tensor([[5,6],
                  [7,8]])
print(A+B,A-B,A*B)
print(torch.sqrt(A))

tensor([[ 6,  8],
        [10, 12]]) tensor([[-4, -4],
        [-4, -4]]) tensor([[ 5, 12],
        [21, 32]])
tensor([[1.0000, 1.4142],
        [1.7321, 2.0000]])


In [ ]:
A = torch.rand(10,10)

B = torch.rand(10,10)
print(A+B,A-B,A*B)

tensor([[0.4894, 0.5224, 1.4275, 1.2618, 1.2268, 0.9381, 1.1541, 1.1959, 1.0804,
         0.4524],
        [0.2750, 0.9329, 1.2268, 0.7115, 1.3882, 1.5227, 0.8593, 0.4638, 0.7961,
         0.4246],
        [0.6115, 0.8224, 1.0461, 0.5101, 0.8521, 1.2156, 1.4380, 0.7666, 1.4499,
         1.5285],
        [0.6997, 1.4491, 1.0867, 1.1265, 0.6219, 0.9372, 1.5482, 1.4391, 1.7157,
         1.3437],
        [0.8976, 0.8398, 1.9040, 1.2374, 1.1168, 0.9970, 0.3981, 1.1358, 0.3945,
         1.2888],
        [0.5317, 0.9689, 1.1332, 1.1529, 1.0230, 0.9959, 0.8076, 0.4446, 1.1129,
         0.9341],
        [1.0841, 1.1542, 0.5430, 0.2965, 0.8749, 1.0622, 0.2203, 1.2250, 1.0339,
         1.8394],
        [0.7072, 1.0906, 1.0876, 1.1218, 1.1423, 0.7890, 0.7282, 1.4847, 1.0588,
         1.2555],
        [1.4867, 0.8337, 0.4949, 0.8746, 1.0739, 0.9689, 1.1247, 1.6125, 0.8168,
         1.1977],
        [0.5348, 1.0249, 0.9574, 0.6246, 1.4878, 0.6500, 0.2638, 1.4182, 0.4601,
         0.5342]]) tensor([[

In [ ]:
A = torch.rand(10,10)
print(torch.mean(A))
print(torch)

tensor(0.4949)
